import {
  AppShell,
  Box,
  Dialog,
  Divider,
  Flex,
  Header,
  Modal,
  Navbar,
  Pagination,
  ScrollArea,
  Space,
  Title
} from "@mantine/core";
import { Card, Image, Text, Button, Group } from "@mantine/core";

import Head from "next/head";
import { useState } from "react";
import { ProductCard } from "~/components/ProductCard";
import type { Product } from "~/types/product";
import { api } from "~/utils/api";

export default function Home() {
  const [categoryFilter, setCategoryFilter] = useState<string | undefined>(
    undefined
  );

  const [page, setPage] = useState(0);

  const { data: productListResponse } = api.product.productList.useQuery({
    category: categoryFilter,
    page,
    perPage: 12,
  });
  const category = api.product.categoryList.useQuery();

  const [productToShowInDialog, setProductToShowInDialog] = useState<Product>();


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <AppShell
          padding="md"
          navbar={
            <Navbar width={{ base: 220 }} p="xs">
              <Navbar.Section mt="xs">{/* Header with logo */}</Navbar.Section>

              <Box>
                <Text
                  align="center"
                  fw={700}
                  fz="xl"
                  variant="gradient"
                  gradient={{ from: "green", to: "blue", deg: 45 }}
                >
                  Categories
                </Text>
                <Space h="md"></Space>
              </Box>
              <Divider />
              <Navbar.Section grow component={ScrollArea} mx="-xs" px="xs">
                {/* Navbar content */}
                <Button.Group orientation="vertical">
                  {category.data?.map((category, idx) => {
                    const isSelected = categoryFilter === category.name;

                    return (
                      <Button
                        onClick={() => {
                          setCategoryFilter(category.name);
                        }}
                        key={idx}
                        variant="subtle"
                        color={isSelected ? "blue" : "dark"}
                      >
                        {category.name}
                      </Button>
                    );
                  })}
                </Button.Group>
              </Navbar.Section>

              <Navbar.Section>{/* Footer with user */}</Navbar.Section>
            </Navbar>
          }
          header={
            <Header height={60} p="xs">
              {/* Header content */}
            </Header>
          }
          styles={(theme) => ({
            main: {
              backgroundColor:
                theme.colorScheme === "dark"
                  ? theme.colors.dark[8]
                  : theme.colors.gray[0],
            },
          })}
        >
          {/* Body */}
          <Flex
            mih={50}
            gap="md"
            justify="center"
            align="flex-start"
            direction="row"
            wrap="wrap"
          >
            {productListResponse?.data.map((product) => {
              return (
                <ProductCard key={product.id} product={product} onClick={() => {setProductToShowInDialog(product)}}  />
              );
            })}
          </Flex>
          <Flex className="mt-auto" justify="center">
            <Pagination
              value={page + 1}
              onChange={(page) => {
                setPage(page - 1);
              }}
              total={productListResponse?.totalPage ?? 0}
            />
          </Flex>
          <Modal
            title={<Title order={3}><Text c='blue'>{productToShowInDialog?.name}</Text></Title>}
            size="lg" radius="md"
            opened={!!productToShowInDialog}
            withCloseButton
            onClose={() => {
              setProductToShowInDialog(undefined);
            }}
            centered
          >
            
            <Text size="sm" mb="xs" weight={500}>
              <Text span c='blue' fw={700}>Description: </Text> 
              {productToShowInDialog?.description}
            </Text>
            <Text size="sm" mb="xs" weight={500}>
              <Text span c='blue' fw={700}>Price: </Text> 
              {productToShowInDialog?.price}
            </Text>
            <Text size="sm" mb="xs" weight={500}>
              <Text span c='blue' fw={700}>Quantity: </Text>  
              {productToShowInDialog?.quantity}
            </Text>
            <Text size="sm" mb="xs" weight={500}>
              <Text span c='blue' fw={700}>Category: </Text>   
              {productToShowInDialog?.category}
            </Text>
          </Modal>
        </AppShell>
      </main>
    </>
  );
}
